# -*- coding: utf-8 -*-
"""06/03/2024.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YKvxPElhWqjODnl90O4O8PzIiT-d8vp-
"""

def saudacao(nome):
  print('Olá', nome)

nome = input("Entre seu nome: ")

saudacao(nome)

def alterna(n):
  mult = 1
  for i in range(n+1):
    print(i * mult , end = '  ')
    mult *= -1

alterna(5)
print( )
alterna(9)
print( )
alterna(12)
print( )

def perimetro_retangulo(a,b):
  per = 2*a + 2*b
  return per

print(f"Perimetro do Retângulo 2 x 3 = {perimetro_retangulo(2,3)}cm ")

def saudacao(nome, mensagem):
  print("Olá", nome, "\b!", mensagem)

# Chamada da função com parâmetros posicionais
saudacao("João", "Como você está?")

# Chamada da função com parâmetros nomeados
saudacao(mensagem ="Tudo bem?", nome ="Maria")

def soma_pn(valores):
  soma_p = 0
  soma_n = 0
  for n in valores:
    if n > 0:
      soma_p += n
    else:
      soma_n += n
  return soma_p, soma_n

valores = [2, -1, 3, -4]
soma_p, soma_n = soma_pn(valores)
print(f"soma dos positivos = {soma_p} soma dos negativos: {soma_n}")